# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:

- stage: Build
  jobs:
  - job: Build_ARM_templates

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)/src/AzureResourceGroup-WebApp-SQL'
        Contents: '**/*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Deploy
  jobs:
  - deployment: DeployArmTemplate
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'FreeOneYear(5f7292bd-e975-43ef-aa61-1871cb2a573d)'
              subscriptionId: '5f7292bd-e975-43ef-aa61-1871cb2a573d'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'AZURE-ARM'
              location: 'East US'
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/drop/WebSiteSQLDatabase.json'
              csmParametersFile: '$(Pipeline.Workspace)/drop/WebSiteSQLDatabase.parameters.json'
              overrideParameters: '-administratorLogin admin1 -administratorLoginPassword $(loginPassword)'
              deploymentMode: 'Incremental'